version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant_law
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./source/data/qdrant_data:/qdrant/storage

configs:
  qdrant_config:
    content: |
      log_level: INFO