version: '3.9'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_law
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./source/data/qdrant_data:/qdrant/storage
    networks:
      - mynetwork

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    environment:
      SA_PASSWORD: "Admin@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - mynetwork

  app:
    build: .
    env_file:
      - .env
    container_name: fast_apilaw
    depends_on:
      - mssql
      - qdrant
    environment:
      DB_HOST: sql_server
      DB_USER: sa
      DB_PASSWORD: Admin@123
      DB_NAME: Law_ChatBot_DB
    ports:
      - "8000:8000"
    volumes:
      - ./source/data/file_db:/initdb   # mount file SQL
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
